#!/usr/bin/env zsh
set -euo pipefail
prefix="$1"
color="$2"
repo="$3"

function process() {
  label="$1"
  if [[ "$label" != "$prefix: "* ]]; then
    return
  fi
  echo -n $label '... '
  gh api \
    "/repos/getsentry/$repo/labels/$label" \
    --method PATCH \
    --input <(echo "{\"color\":\"$color\"}") | jq .color -r
}

_IFS=$IFS
IFS=$'\n'
for name in $(jq -r '.[].name' $repo); do
  process $name
done
IFS=$_IFS
unset _IFS
